---
server:
  port: 8080

spring:
  datasource:
    url: jdbc:postgresql://localhost:5433/monitoring_system
    username: postgres
    password: 1234
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

security:
  jwt:
    secret: c2VsZ25kZmxrbi4geGFzZGdqZXJ3Z25sZGZ2LixjbmJvZHJzW11ma2pkbmNrLnZuYmdqO3Nsbix4bGt2am5rbXZkemtudm1zc2ZnZnNmc25zZGZkZmZzZnNkZmZzZGZzZA==
    access: 3600000
    refresh: 2592000000