server:
  port: 8082

spring:
  application:
    name: sensor-data-generator

monitoring:
  service:
    data-receiver:
      url: http://localhost:8081/api/v1/internal/sensor-data/receive

generator:
  schedule:
    fixedRate:
      ms: 5000
  smooth:
    max-step-percentage: 0.2
  event:
    warning:
      chance: 0.05
      duration:
        ticks: 1
    critical:
      chance: 0.03
      duration:
        ticks: 1