server:
  port: 8082

spring:
  application:
    name: sensor-data-generator

monitoring:
  service:
    data-receiver:
      url: http://localhost:8081/api/v1/internal/sensor-data/receive

generator:
  schedule:
    fixedRate:
      ms: 5000